### ISSUE TITLE
Thanks! Screenshot?

### ISSUE THREAD

**Issue by bitwombat** [Anfid/dotawesome#1]
Thanks for sharing your config! Would it be too much to ask to put a screenshot up?

Also, what's 'cosy' do? Oddly, Googling "cosy lua" brings up a musician...

**Comment by Anfid** [comment]
Cosy is a library name I came up to keep config modular. It does not depend on my own preferences and can be reused, if you love some of my widgets or layouts. I also decided to keep util functions there. Also note, that some of the widgets are not yet polished, except for desktop.cava.

I will try to create a readme and upload a screenshot later this day

**Comment by Anfid** [comment]
Took a bit longer than I wanted to, but here you go. Some screenshots were added to README file
