### ISSUE TITLE
Do you have dotfiles for conky?

### ISSUE THREAD

**Issue by thepenguinthatwants** [Anfid/dotawesome#2]
I've being trying to get conky to work with awesome for a while with no success.

**Comment by Anfid** [comment]
Sure thing. If you are interested in the exact conky setup I used for my screenshot, it was last present on commit 8373340f402f4a97ea3870a4729ebc537f0d827f.
The script that I used to start it up is [startup.sh](https://github.com/Anfid/dotawesome/blob/8373340f402f4a97ea3870a4729ebc537f0d827f/startup.sh). It is called [here](https://github.com/Anfid/dotawesome/blob/8373340f402f4a97ea3870a4729ebc537f0d827f/rc.lua#L320).

The conky config itself can be found in separate repository, where I keep shared config between all WMs: [dotfiles].(https://github.com/Anfid/dotfiles)
The config dir itself: [home/.config/conky](https://github.com/Anfid/dotfiles/tree/master/home/.config/conky).

However, now I decided to stray away from conky and write similar native awesome widgets, they are much more extensible. Although at this moment they are far from complete, you can find CPU, RAM monitoring and cava visualizer [here](https://github.com/Anfid/cosy/tree/0a073c9b54f9b078e42cbe0d47e0e57807d5f329/widget/desktop). Notable improvements are widget scaling with monitor DPI, automatic adjustment to awesome theme colors and automatic adjustment to CPU core count for easier use across different machines. These widgets initialization can be easily found in current master, in [rc.lua](https://github.com/Anfid/dotawesome/blob/master/rc.lua).
